spring:
  application:
    name: front-service
server:
  port: 3000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false